name: "ci"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install latex stuff
        run: sudo apt-get install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super texlive-latex-base
      - name: Install dependencies
        run: uv sync --all-extras
      - name: check formatting
        run: uv run ruff format --check
      - name: check linting
        run: uv run ruff check
      - name: check types
        run: uv run pyright
      - name: run tests
        run: uv run pytest tests
      - name: build
        run: uv build
